"use strict";
const assert = require("assert");
const core = require("../assets/v360-core.js");
assert.equal(core.wrap(-1, 32), 31);
assert.equal(core.wrap(32, 32), 0);
assert.equal(core.mapIndex(0, 32, 64), 0);
assert.equal(core.mapIndex(16, 32, 64), 32);
assert.equal(core.frameFromDrag(5, 24, 8, 32), 8);
const timeline = new core.SharedTimeline(32);
timeline.setFrame(31);
timeline.step(1);
assert.equal(timeline.frame, 0);
timeline.reverse();
timeline.step(1);
assert.equal(timeline.frame, 31);
timeline.setCount(64, true);
assert.ok(timeline.frame >= 61 && timeline.frame <= 63);
console.log("V360 core synchronization tests: PASS");
